### ISSUE TITLE
Can't run mac build on mac os Catalina.

### ISSUE THREAD

**Issue by PushoN** [snatvb/leo-ecs-remote-debugger#2]

**Comment by Leopotam** [comment]
Any info about how it cant run? There are 2 possible reasons:
* System protection from unsigned apps. Solution: Right click, select "Open" from context menu and select "Open" at warning popup.
* No "execute" attribute on binary file. Solution: Right click, select "Show contents", navigate to /Contents/MacOS/LeoEcsRemoteDebugger", then open terminal, write "chmod +x " and drag& drop this file to terminal, press enter.

I tried it right now - first solution should works.

**Comment by Leopotam** [comment]
@PushoN is issue fixed?
